# Generated by Django 4.2.6 on 2023-10-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('categoria_empresa', models.CharField(max_length=100)),
                ('quitado', models.BooleanField()),
                ('data', models.DateField(auto_now_add=True)),
                ('stand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finecap.stand')),
            ],
        ),
    ]
